# https://github.com/char-lie/software_design
language:
  python
python:
  2.7
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c "create user test_user with password '123';" -U postgres
  - psql -c "create database test_db_hotel owner test_user;" -U postgres
  - psql -c "create database test_db_booking owner test_user;" -U postgres
script:
  - ./tests.sh

