# https://github.com/char-lie/software_design
language:
  python
python:
  2.7
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
    pip install fake-factory
before_script:
  - psql -f migrations/create_dbs.sql -U postgres
  - psql -f migrations/migrations_hotel.sql -U postgres -d test_db_hotel
  - psql -f migrations/migrations_fly.sql -U postgres -d test_db_fly
script:
  - ./tests.sh
after_script:
  - psql -f migrations/drop_dbs.sql -U postgres

