# https://github.com/char-lie/software_design
language:
  python
python:
  2.7
addons:
  postgresql: "9.4"
services:
  - postgresql
before_install:
  - sudo apt-get install postgresql-server-dev-all
  - sudo sed 's/#max_prepared_transactions = 0/max_prepared_transactions = 5/g' -i /etc/postgresql/*/main/postgresql.conf
  - sudo service postgresql restart
install:
  - pip install fake-factory psycopg2
before_script:
  - psql -f migrations/create_dbs.sql -U postgres
  - psql -f migrations/migrations_hotel.sql -U postgres -d test_db_hotel
  - psql -f migrations/migrations_fly.sql -U postgres -d test_db_fly
script:
  - python -m tests
after_script:
  - psql -f migrations/drop_dbs.sql -U postgres

